### PR TITLE
Use page component

### PR DESCRIPTION
**Pull request by frozenhelium**
* Add page margin variable
* Use page component in
    * Arys
    * ClusterViz
    * Dashboard
    * EditEntries
    * Export
    * LeadAdd
    * LeadGroups
    * LeadsViz
    * UserExports
    * UserProfile
    * ProjectDenied
    * Visualization

### CODE REVIEW

**Comment by tnagorra** [comment]
Problem in Countries page
grim_2019-01-31-122355

Bad border style
grim_2019-01-31-122959

Overflow problem; Loading animation is also sqashed
grim_2019-01-31-123115

Doesn't take full space. (Try zooming out)
grim_2019-01-31-123259

Looks weird after zoom change
grim_2019-01-31-123419

Shouldn't navbar
grim_2019-01-31-123548

**Comment by eoglethorpe** [comment]
#amaturedeveloper

**Comment by eoglethorpe** [comment]
on a serious note, what's the thinking behind the page component here?

**Comment by tnagorra** [comment]
We create a common component to share styling and behavior for pages like: Header, Footer, Sidebar, MainContent.
It should decrease inconsistency between pages and decrease duplicate logic.

**Pull request closed without merging**
